
# cargo-vet audits file

[[audits.clap]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "4.6.4"

[[audits.clap_builder]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "4.6.2"

[[audits.clap_derive]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "4.6.4"

[[audits.futures-core]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.3.33"

[[audits.futures-task]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.3.33"

[[audits.futures-util]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.3.33"

[[audits.proc-macro2]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.0.107"

[[audits.protobuf-forensic-core]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.1.1"

[[audits.quote]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.0.47"

[[audits.serde]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.0.229"

[[audits.serde_core]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.0.229"

[[audits.serde_derive]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.0.229"

[[audits.serde_json]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.0.151"

[[audits.simd-adler32]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.3.10"

[[audits.snap]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.1.2"

[[audits.syn]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "2.0.119"

[[audits.syn]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "3.0.3"

[[audits.thiserror]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "2.0.19"

[[audits.thiserror-impl]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "2.0.19"

[[audits.time]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.3.54"

[[audits.time-macros]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.2.32"

[[audits.uuid]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.24.0"

[[audits.zmij]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.0.23"
